import { DataEntity } from "./services/types";

export const rawData: Record<string, DataEntity[]> = {
  meals: [
    {
      idMeal: "52977",
      strMeal: "Corba",
      strDrinkAlternate: "",
      strCategory: "Side",
      strArea: "Turkish",
      strInstructions:
        "Pick through your lentils for any foreign debris, rinse them 2 or 3 times, drain, and set aside.  Fair warning, this will probably turn your lentils into a solid block that you’ll have to break up later\r\nIn a large pot over medium-high heat, sauté the olive oil and the onion with a pinch of salt for about 3 minutes, then add the carrots and cook for another 3 minutes.\r\nAdd the tomato paste and stir it around for around 1 minute. Now add the cumin, paprika, mint, thyme, black pepper, and red pepper as quickly as you can and stir for 10 seconds to bloom the spices. Congratulate yourself on how amazing your house now smells.\r\nImmediately add the lentils, water, broth, and salt. Bring the soup to a (gentle) boil.\r\nAfter it has come to a boil, reduce heat to medium-low, cover the pot halfway, and cook for 15-20 minutes or until the lentils have fallen apart and the carrots are completely cooked.\r\nAfter the soup has cooked and the lentils are tender, blend the soup either in a blender or simply use a hand blender to reach the consistency you desire. Taste for seasoning and add more salt if necessary.\r\nServe with crushed-up crackers, torn up bread, or something else to add some extra thickness.  You could also use a traditional thickener (like cornstarch or flour), but I prefer to add crackers for some texture and saltiness.  Makes great leftovers, stays good in the fridge for about a week.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/58oia61564916529.jpg",
      strTags: "Soup",
      strYoutube: "https://www.youtube.com/watch?v=VVnZd8A84z4",
      strIngredient1: "Lentils",
      strIngredient2: "Onion",
      strIngredient3: "Carrots",
      strIngredient4: "Tomato Puree",
      strIngredient5: "Cumin",
      strIngredient6: "Paprika",
      strIngredient7: "Mint",
      strIngredient8: "Thyme",
      strIngredient9: "Black Pepper",
      strIngredient10: "Red Pepper Flakes",
      strIngredient11: "Vegetable Stock",
      strIngredient12: "Water",
      strIngredient13: "Sea Salt",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "1 cup ",
      strMeasure2: "1 large",
      strMeasure3: "1 large",
      strMeasure4: "1 tbs",
      strMeasure5: "2 tsp",
      strMeasure6: "1 tsp ",
      strMeasure7: "1/2 tsp",
      strMeasure8: "1/2 tsp",
      strMeasure9: "1/4 tsp",
      strMeasure10: "1/4 tsp",
      strMeasure11: "4 cups ",
      strMeasure12: "1 cup ",
      strMeasure13: "Pinch",
      strMeasure14: " ",
      strMeasure15: " ",
      strMeasure16: " ",
      strMeasure17: " ",
      strMeasure18: " ",
      strMeasure19: " ",
      strMeasure20: " ",
      strSource:
        "https://findingtimeforcooking.com/main-dishes/red-lentil-soup-corba/",
      strImageSource: "",
      strCreativeCommonsConfirmed: "",
      dateModified: "",
    },
    {
      idMeal: "53060",
      strMeal: "Burek",
      strDrinkAlternate: "",
      strCategory: "Side",
      strArea: "Croatian",
      strInstructions:
        "Fry the finely chopped onions and minced meat in oil. Add the salt and pepper. Grease a round baking tray and put a layer of pastry in it. Cover with a thin layer of filling and cover this with another layer of filo pastry which must be well coated in oil. Put another layer of filling and cover with pastry. When you have five or six layers, cover with filo pastry, bake at 200ºC/392ºF for half an hour and cut in quarters and serve.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/tkxquw1628771028.jpg",
      strTags: "Streetfood, Onthego",
      strYoutube: "https://www.youtube.com/watch?v=YsJXZwE5pdY",
      strIngredient1: "Filo Pastry",
      strIngredient2: "Minced Beef",
      strIngredient3: "Onion",
      strIngredient4: "Oil",
      strIngredient5: "Salt",
      strIngredient6: "Pepper",
      strIngredient7: "",
      strIngredient8: "",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "1 Packet",
      strMeasure2: "150g",
      strMeasure3: "150g",
      strMeasure4: "40g",
      strMeasure5: "Dash",
      strMeasure6: "Dash",
      strMeasure7: " ",
      strMeasure8: " ",
      strMeasure9: " ",
      strMeasure10: " ",
      strMeasure11: " ",
      strMeasure12: " ",
      strMeasure13: " ",
      strMeasure14: " ",
      strMeasure15: " ",
      strMeasure16: " ",
      strMeasure17: " ",
      strMeasure18: " ",
      strMeasure19: " ",
      strMeasure20: " ",
      strSource:
        "https://www.visit-croatia.co.uk/croatian-cuisine/croatian-recipes/",
      strImageSource: "",
      strCreativeCommonsConfirmed: "",
      dateModified: "",
    },
    {
      idMeal: "53065",
      strMeal: "Sushi",
      strDrinkAlternate: "",
      strCategory: "Seafood",
      strArea: "Japanese",
      strInstructions:
        "STEP 1\r\nTO MAKE SUSHI ROLLS: Pat out some rice. Lay a nori sheet on the mat, shiny-side down. Dip your hands in the vinegared water, then pat handfuls of rice on top in a 1cm thick layer, leaving the furthest edge from you clear.\r\n\r\nSTEP 2\r\nSpread over some Japanese mayonnaise. Use a spoon to spread out a thin layer of mayonnaise down the middle of the rice.\r\n\r\nSTEP 3\r\nAdd the filling. Get your child to top the mayonnaise with a line of their favourite fillings – here we’ve used tuna and cucumber.\r\n\r\nSTEP 4\r\nRoll it up. Lift the edge of the mat over the rice, applying a little pressure to keep everything in a tight roll.\r\n\r\nSTEP 5\r\nStick down the sides like a stamp. When you get to the edge without any rice, brush with a little water and continue to roll into a tight roll.\r\n\r\nSTEP 6\r\nWrap in cling film. Remove the mat and roll tightly in cling film before a grown-up cuts the sushi into thick slices, then unravel the cling film.\r\n\r\nSTEP 7\r\nTO MAKE PRESSED SUSHI: Layer over some smoked salmon. Line a loaf tin with cling film, then place a thin layer of smoked salmon inside on top of the cling film.\r\n\r\nSTEP 8\r\nCover with rice and press down. Press about 3cm of rice over the fish, fold the cling film over and press down as much as you can, using another tin if you have one.\r\n\r\nSTEP 9\r\nTip it out like a sandcastle. Turn block of sushi onto a chopping board. Get a grown-up to cut into fingers, then remove the cling film.\r\n\r\nSTEP 10\r\nTO MAKE SUSHI BALLS: Choose your topping. Get a small square of cling film and place a topping, like half a prawn or a small piece of smoked salmon, on it. Use damp hands to roll walnut-sized balls of rice and place on the topping.\r\n\r\nSTEP 11\r\nMake into tight balls. Bring the corners of the cling film together and tighten into balls by twisting it up, then unwrap and serve.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/g046bb1663960946.jpg",
      strTags: "",
      strYoutube: "https://www.youtube.com/watch?v=ub68OxEypaY",
      strIngredient1: "Sushi Rice",
      strIngredient2: "Rice wine",
      strIngredient3: "Caster Sugar",
      strIngredient4: "Mayonnaise",
      strIngredient5: "Rice wine",
      strIngredient6: "Soy Sauce",
      strIngredient7: "Cucumber",
      strIngredient8: "",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "300ml ",
      strMeasure2: "100ml",
      strMeasure3: "2 tbs",
      strMeasure4: "3 tbs",
      strMeasure5: "1 tbs",
      strMeasure6: "1 tbs",
      strMeasure7: "1",
      strMeasure8: " ",
      strMeasure9: " ",
      strMeasure10: " ",
      strMeasure11: " ",
      strMeasure12: " ",
      strMeasure13: " ",
      strMeasure14: " ",
      strMeasure15: " ",
      strMeasure16: " ",
      strMeasure17: " ",
      strMeasure18: " ",
      strMeasure19: " ",
      strMeasure20: " ",
      strSource: "https://www.bbcgoodfood.com/recipes/simple-sushi",
      strImageSource: "",
      strCreativeCommonsConfirmed: "",
      dateModified: "",
    },
    {
      idMeal: "52978",
      strMeal: "Kumpir",
      strDrinkAlternate: "",
      strCategory: "Side",
      strArea: "Turkish",
      strInstructions:
        "If you order kumpir in Turkey, the standard filling is first, lots of butter mashed into the potato, followed by cheese. There’s then a row of other toppings that you can just point at to your heart’s content – sweetcorn, olives, salami, coleslaw, Russian salad, allsorts – and you walk away with an over-stuffed potato because you got ever-excited by the choices on offer.\r\n\r\nGrate (roughly – you can use as much as you like) 150g of cheese.\r\nFinely chop one onion and one sweet red pepper.\r\nPut these ingredients into a large bowl with a good sprinkling of salt and pepper, chilli flakes (optional).",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/mlchx21564916997.jpg",
      strTags: "SideDish",
      strYoutube: "https://www.youtube.com/watch?v=IEDEtZ4UVtI",
      strIngredient1: "Potatoes",
      strIngredient2: "Butter",
      strIngredient3: "Cheese",
      strIngredient4: "Onion",
      strIngredient5: "Red Pepper",
      strIngredient6: "Red Chile Flakes",
      strIngredient7: "",
      strIngredient8: "",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "2 large",
      strMeasure2: "2 tbs",
      strMeasure3: "150g",
      strMeasure4: "1 large",
      strMeasure5: "1 large",
      strMeasure6: "Pinch",
      strMeasure7: " ",
      strMeasure8: " ",
      strMeasure9: " ",
      strMeasure10: " ",
      strMeasure11: " ",
      strMeasure12: " ",
      strMeasure13: " ",
      strMeasure14: " ",
      strMeasure15: " ",
      strMeasure16: " ",
      strMeasure17: " ",
      strMeasure18: " ",
      strMeasure19: " ",
      strMeasure20: " ",
      strSource:
        "http://www.turkeysforlife.com/2013/10/firinda-kumpir-turkish-street-food.html",
      strImageSource: "",
      strCreativeCommonsConfirmed: "",
      dateModified: "",
    },
    {
      idMeal: "53026",
      strMeal: "Tamiya",
      strDrinkAlternate: "",
      strCategory: "Vegetarian",
      strArea: "Egyptian",
      strInstructions:
        "oak the beans in water to cover overnight.Drain. If skinless beans are unavailable, rub to loosen the skins, then discard the skins. Pat the beans dry with a towel.\r\nGrind the beans in a food mill or meat grinder.If neither appliance is available, process them in a food processor but only until the beans form a paste. (If blended too smoothly, the batter tends to fall apart during cooking.) Add the scallions, garlic, cilantro, cumin, baking powder, cayenne, salt, pepper, and coriander, if using.  Refrigerate for at least 30 minutes.\r\nShape the bean mixture into 1-inch balls.Flatten slightly and coat with flour.\r\nHeat at least 1½-inches of oil over medium heat to 365 degrees.\r\nFry the patties in batches, turning once, until golden brown on all sides, about 5 minutes.Remove with a wire mesh skimmer or slotted spoon. Serve as part of a meze or in pita bread with tomato-cucumber salad and tahina sauce.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/n3xxd91598732796.jpg",
      strTags: "",
      strYoutube: "https://www.youtube.com/watch?v=mulqW-J3Yy4",
      strIngredient1: "Broad Beans",
      strIngredient2: "Spring Onions",
      strIngredient3: "Garlic Clove",
      strIngredient4: "Parsley",
      strIngredient5: "Cumin",
      strIngredient6: "Baking Powder",
      strIngredient7: "Cayenne Pepper",
      strIngredient8: "Flour",
      strIngredient9: "Vegetable Oil",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "3 cups ",
      strMeasure2: "6",
      strMeasure3: "4",
      strMeasure4: "1/4 cup",
      strMeasure5: "2 tsp",
      strMeasure6: "1 tsp ",
      strMeasure7: "1/2 tsp",
      strMeasure8: "Spinkling",
      strMeasure9: "As required",
      strMeasure10: " ",
      strMeasure11: " ",
      strMeasure12: " ",
      strMeasure13: " ",
      strMeasure14: " ",
      strMeasure15: " ",
      strMeasure16: " ",
      strMeasure17: " ",
      strMeasure18: " ",
      strMeasure19: " ",
      strMeasure20: " ",
      strSource:
        "https://oukosher.org/recipes/tamiya-egyptian-dried-fava-bean-fritters/",
      strImageSource: "",
      strCreativeCommonsConfirmed: "",
      dateModified: "",
    },
    {
      idMeal: "52785",
      strMeal: "Dal fry",
      strDrinkAlternate: "",
      strCategory: "Vegetarian",
      strArea: "Indian",
      strInstructions:
        "Wash and soak toor dal in approx. 3 cups of water, for at least one hours. Dal will be double in volume after soaking. Drain the water.\r\nCook dal with 2-1/2 cups water and add salt, turmeric, on medium high heat, until soft in texture (approximately 30 mins) it should be like thick soup.\r\nIn a frying pan, heat the ghee. Add cumin seeds, and mustard seeds. After the seeds crack, add bay leaves, green chili, ginger and chili powder. Stir for a few seconds.\r\nAdd tomatoes, salt and sugar stir and cook until tomatoes are tender and mushy.\r\nAdd cilantro and garam masala cook for about one minute.\r\nPour the seasoning over dal mix it well and cook for another minute.\r\nServe with Naan.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/wuxrtu1483564410.jpg",
      strTags: "Curry,Vegetarian,Cake",
      strYoutube: "https://www.youtube.com/watch?v=J4D855Q9-jg",
      strIngredient1: "Toor dal",
      strIngredient2: "Water",
      strIngredient3: "Salt",
      strIngredient4: "Turmeric",
      strIngredient5: "Ghee",
      strIngredient6: "Chopped tomatoes",
      strIngredient7: "Cumin seeds",
      strIngredient8: "Mustard Seeds",
      strIngredient9: "Bay Leaf",
      strIngredient10: "Green Chili",
      strIngredient11: "Ginger",
      strIngredient12: "Cilantro",
      strIngredient13: "Red Pepper",
      strIngredient14: "Salt",
      strIngredient15: "Sugar",
      strIngredient16: "Garam Masala",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "1 cup",
      strMeasure2: "2-1/2 cups",
      strMeasure3: "1 tsp",
      strMeasure4: "1/4 tsp",
      strMeasure5: "3 tbs",
      strMeasure6: "1 cup",
      strMeasure7: "1/2 tsp",
      strMeasure8: "1/2 tsp",
      strMeasure9: "2",
      strMeasure10: "1 tbs chopped",
      strMeasure11: "2 tsp shredded",
      strMeasure12: "2 tbs ",
      strMeasure13: "1/2 tsp",
      strMeasure14: "1/2 tsp",
      strMeasure15: "1 tsp",
      strMeasure16: "1/4 tsp",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
      strSource: "https://www.instagram.com/p/BO21bpYD3Fu",
      strImageSource: "",
      strCreativeCommonsConfirmed: "",
      dateModified: "",
    },
    {
      idMeal: "52804",
      strMeal: "Poutine",
      strDrinkAlternate: "",
      strCategory: "Miscellaneous",
      strArea: "Canadian",
      strInstructions:
        "Heat oil in a deep fryer or deep heavy skillet to 365°F (185°C).\r\nWarm gravy in saucepan or microwave.\r\nPlace the fries into the hot oil, and cook until light brown, about 5 minutes.\r\nRemove to a paper towel lined plate to drain.\r\nPlace the fries on a serving platter, and sprinkle the cheese over them.\r\nLadle gravy over the fries and cheese, and serve immediately.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/uuyrrx1487327597.jpg",
      strTags: "UnHealthy,Speciality,HangoverFood",
      strYoutube: "https://www.youtube.com/watch?v=UVAMAoA2_WU",
      strIngredient1: "Vegetable Oil",
      strIngredient2: "Beef Gravy",
      strIngredient3: "Potatoes",
      strIngredient4: "Cheese Curds",
      strIngredient5: "",
      strIngredient6: "",
      strIngredient7: "",
      strIngredient8: "",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "Dash",
      strMeasure2: "1 Can",
      strMeasure3: "5 thin cut",
      strMeasure4: "2 cups",
      strMeasure5: "",
      strMeasure6: "",
      strMeasure7: "",
      strMeasure8: "",
      strMeasure9: "",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
      strSource: "http://www.food.com/recipe/real-canadian-poutine-113388",
      strImageSource: "",
      strCreativeCommonsConfirmed: "",
      dateModified: "",
    },
    {
      idMeal: "52844",
      strMeal: "Lasagne",
      strDrinkAlternate: "",
      strCategory: "Pasta",
      strArea: "Italian",
      strInstructions:
        "Heat the oil in a large saucepan. Use kitchen scissors to snip the bacon into small pieces, or use a sharp knife to chop it on a chopping board. Add the bacon to the pan and cook for just a few mins until starting to turn golden. Add the onion, celery and carrot, and cook over a medium heat for 5 mins, stirring occasionally, until softened.\r\nAdd the garlic and cook for 1 min, then tip in the mince and cook, stirring and breaking it up with a wooden spoon, for about 6 mins until browned all over.\r\nStir in the tomato purée and cook for 1 min, mixing in well with the beef and vegetables. Tip in the chopped tomatoes. Fill each can half full with water to rinse out any tomatoes left in the can, and add to the pan. Add the honey and season to taste. Simmer for 20 mins.\r\nHeat oven to 200C/180C fan/gas 6. To assemble the lasagne, ladle a little of the ragu sauce into the bottom of the roasting tin or casserole dish, spreading the sauce all over the base. Place 2 sheets of lasagne on top of the sauce overlapping to make it fit, then repeat with more sauce and another layer of pasta. Repeat with a further 2 layers of sauce and pasta, finishing with a layer of pasta.\r\nPut the crème fraîche in a bowl and mix with 2 tbsp water to loosen it and make a smooth pourable sauce. Pour this over the top of the pasta, then top with the mozzarella. Sprinkle Parmesan over the top and bake for 25–30 mins until golden and bubbling. Serve scattered with basil, if you like.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/wtsvxx1511296896.jpg",
      strTags: "",
      strYoutube: "https://www.youtube.com/watch?v=gfhfsBPt46s",
      strIngredient1: "Olive Oil",
      strIngredient2: "Bacon",
      strIngredient3: "Onion",
      strIngredient4: "Celery",
      strIngredient5: "Carrots",
      strIngredient6: "Garlic",
      strIngredient7: "Minced Beef",
      strIngredient8: "Tomato Puree",
      strIngredient9: "Chopped Tomatoes",
      strIngredient10: "Honey",
      strIngredient11: "Lasagne Sheets",
      strIngredient12: "Creme Fraiche",
      strIngredient13: "Mozzarella Balls",
      strIngredient14: "Parmesan Cheese",
      strIngredient15: "Basil Leaves",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "1 tblsp ",
      strMeasure2: "2",
      strMeasure3: "1 finely chopped ",
      strMeasure4: "1 Stick",
      strMeasure5: "1 medium",
      strMeasure6: "2 cloves chopped",
      strMeasure7: "500g",
      strMeasure8: "1 tbls",
      strMeasure9: "800g",
      strMeasure10: "1 tblsp ",
      strMeasure11: "500g",
      strMeasure12: "400ml",
      strMeasure13: "125g",
      strMeasure14: "50g",
      strMeasure15: "Topping",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
      strSource: "https://www.bbcgoodfood.com/recipes/classic-lasagne",
      strImageSource: "",
      strCreativeCommonsConfirmed: "",
      dateModified: "",
    },
    {
      idMeal: "52929",
      strMeal: "Timbits",
      strDrinkAlternate: "",
      strCategory: "Dessert",
      strArea: "Canadian",
      strInstructions:
        "Sift together dry ingredients.\r\nMix together wet ingredients and incorporate into dry. Stir until smooth.\r\nDrop by teaspoonfuls(no bigger) into hot oil (365 degrees, no hotter), turning after a few moments until golden brown on all sides.\r\nRemove and drain.\r\nRoll in cinnamon sugar while still warm and serve.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/txsupu1511815755.jpg",
      strTags: "Snack,Treat",
      strYoutube: "https://www.youtube.com/watch?v=fFLn1h80AGQ",
      strIngredient1: "Flour",
      strIngredient2: "Sugar",
      strIngredient3: "Baking Powder",
      strIngredient4: "Salt",
      strIngredient5: "Egg",
      strIngredient6: "Milk",
      strIngredient7: "Oil",
      strIngredient8: "Oil",
      strIngredient9: "Icing Sugar",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "2 cups ",
      strMeasure2: "1/3 cup",
      strMeasure3: "3 tsp",
      strMeasure4: "½ tsp",
      strMeasure5: "1 beaten",
      strMeasure6: "¾ cup",
      strMeasure7: "3 tbs",
      strMeasure8: "for frying",
      strMeasure9: "garnish",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
      strSource: "http://www.geniuskitchen.com/recipe/drop-doughnuts-133877",
      strImageSource: "",
      strCreativeCommonsConfirmed: "",
      dateModified: "",
    },
    {
      idMeal: "52948",
      strMeal: "Wontons",
      strDrinkAlternate: "",
      strCategory: "Pork",
      strArea: "Chinese",
      strInstructions:
        "Combine pork, garlic, ginger, soy sauce, sesame oil, and vegetables in a bowl.\r\nSeparate wonton skins.\r\nPlace a heaping teaspoon of filling in the center of the wonton.\r\nBrush water on 2 borders of the skin, covering 1/4 inch from the edge.\r\nFold skin over to form a triangle, sealing edges.\r\nPinch the two long outside points together.\r\nHeat oil to 450 degrees and fry 4 to 5 at a time until golden.\r\nDrain and serve with sauce.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/1525876468.jpg",
      strTags: "MainMeal",
      strYoutube: "https://www.youtube.com/watch?v=9h9No18ZyCI",
      strIngredient1: "Pork",
      strIngredient2: "Garlic Clove",
      strIngredient3: "Ginger",
      strIngredient4: "Soy Sauce",
      strIngredient5: "Sesame Seed Oil",
      strIngredient6: "Carrots",
      strIngredient7: "Celery",
      strIngredient8: "Spring Onions",
      strIngredient9: "Wonton Skin",
      strIngredient10: "Oil",
      strIngredient11: "Water",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "1lb",
      strMeasure2: "3 chopped",
      strMeasure3: "1 tsp ",
      strMeasure4: "1 tbs",
      strMeasure5: "1 tsp ",
      strMeasure6: "3 finely chopped",
      strMeasure7: "3 finely chopped",
      strMeasure8: "6 chopped",
      strMeasure9: "1 Packet",
      strMeasure10: "Fry",
      strMeasure11: "Bottle",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
      strSource: "http://www.geniuskitchen.com/recipe/chinese-wontons-20235",
      strImageSource: "",
      strCreativeCommonsConfirmed: "",
      dateModified: "",
    },
    {
      idMeal: "52971",
      strMeal: "Kafteji",
      strDrinkAlternate: "",
      strCategory: "Vegetarian",
      strArea: "Tunisian",
      strInstructions:
        "Peel potatoes and cut into 5cm cubes.\r\nPour 1-2 cm of olive oil into a large pan and heat up very hot. Fry potatoes until golden brown for 20 minutes, turning from time to time. Place on kitchen paper to drain.\r\nCut the peppers in half and remove seeds. Rub a little olive oil on them and place the cut side down on a baking tray. Place them under the grill. Grill until the skin is dark and bubbly. While the peppers are still hot, put them into a plastic sandwich bag and seal it. Take them out after 15 minutes and remove skins.\r\nIn the meantime, heat more olive oil another pan. Peel the onions and cut into thin rings. Fry for 15 minutes until golden brown, turning them often. Add the Ras el hanout at the end.\r\nCut the pumpkin into 5cm cubes and fry in the same pan you used for the potatoes for 10-15 minutes until it is soft and slightly browned. Place on kitchen paper.\r\nPour the remaining olive oil out of the pan and put all the cooked vegetables into the pan and mix. Whisk eggs and pour them over the vegetables. Put the lid on the pan so that the eggs cook. Put the contents of the pan onto a large chopping board, add salt and pepper and chopped and mix everything with a big knife.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/1bsv1q1560459826.jpg",
      strTags: "",
      strYoutube: "https://www.youtube.com/watch?v=-TFf-Zu-xQU",
      strIngredient1: "Potatoes",
      strIngredient2: "Olive Oil",
      strIngredient3: "Green Pepper",
      strIngredient4: "Onions",
      strIngredient5: "Ras el hanout",
      strIngredient6: "Pumpkin",
      strIngredient7: "Eggs",
      strIngredient8: "Salt",
      strIngredient9: "Pepper",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "5 Large",
      strMeasure2: "2 tbs",
      strMeasure3: "1",
      strMeasure4: "5",
      strMeasure5: "1 tbs",
      strMeasure6: "500g",
      strMeasure7: "24 Skinned",
      strMeasure8: "Pinch",
      strMeasure9: "Pinch",
      strMeasure10: " ",
      strMeasure11: " ",
      strMeasure12: " ",
      strMeasure13: " ",
      strMeasure14: " ",
      strMeasure15: " ",
      strMeasure16: " ",
      strMeasure17: " ",
      strMeasure18: " ",
      strMeasure19: " ",
      strMeasure20: " ",
      strSource:
        "http://allrecipes.co.uk/recipe/12294/kafteji--tunisian-fried-vegetables-.aspx",
      strImageSource: "",
      strCreativeCommonsConfirmed: "",
      dateModified: "",
    },
    {
      idMeal: "53013",
      strMeal: "Big Mac",
      strDrinkAlternate: "",
      strCategory: "Beef",
      strArea: "American",
      strInstructions:
        "For the Big Mac sauce, combine all the ingredients in a bowl, season with salt and chill until ready to use.\r\n2. To make the patties, season the mince with salt and pepper and form into 4 balls using about 1/3 cup mince each. Place each onto a square of baking paper and flatten to form into four x 15cm circles. Heat oil in a large frypan over high heat. In 2 batches, cook beef patties for 1-2 minutes each side until lightly charred and cooked through. Remove from heat and keep warm. Repeat with remaining two patties.\r\n3. Carefully slice each burger bun into three acrossways, then lightly toast.\r\n4. To assemble the burgers, spread a little Big Mac sauce over the bottom base. Top with some chopped onion, shredded lettuce, slice of cheese, beef patty and some pickle slices. Top with the middle bun layer, and spread with more Big Mac sauce, onion, lettuce, pickles, beef patty and then finish with more sauce. Top with burger lid to serve.\r\n5. After waiting half an hour for your food to settle, go for a jog.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/urzj1d1587670726.jpg",
      strTags: "",
      strYoutube: "https://www.youtube.com/watch?v=C5J39YnnPsg",
      strIngredient1: "Minced Beef",
      strIngredient2: "Olive Oil",
      strIngredient3: "Sesame Seed Burger Buns",
      strIngredient4: "Onion",
      strIngredient5: "Iceberg Lettuce",
      strIngredient6: "Cheese",
      strIngredient7: "Dill Pickles",
      strIngredient8: "Mayonnaise",
      strIngredient9: "White Wine Vinegar",
      strIngredient10: "Pepper",
      strIngredient11: "Mustard",
      strIngredient12: "Onion Salt",
      strIngredient13: "Garlic Powder",
      strIngredient14: "Paprika",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "400g",
      strMeasure2: "2 tbs",
      strMeasure3: "2",
      strMeasure4: "Chopped",
      strMeasure5: "1/4 ",
      strMeasure6: "2 sliced",
      strMeasure7: "2 large",
      strMeasure8: "1 cup ",
      strMeasure9: "2 tsp",
      strMeasure10: "Pinch",
      strMeasure11: "2 tsp",
      strMeasure12: "1 1/2 tsp ",
      strMeasure13: "1 1/2 tsp ",
      strMeasure14: "1/2 tsp",
      strMeasure15: " ",
      strMeasure16: " ",
      strMeasure17: " ",
      strMeasure18: " ",
      strMeasure19: " ",
      strMeasure20: " ",
      strSource:
        "https://www.delicious.com.au/recipes/finally-recipe-worlds-top-selling-burger-big-mac/5221ee4a-279e-4a0b-8629-f442dc46822e",
      strImageSource: "",
      strCreativeCommonsConfirmed: "",
      dateModified: "",
    },
    {
      idMeal: "53027",
      strMeal: "Koshari",
      strDrinkAlternate: "",
      strCategory: "Vegetarian",
      strArea: "Egyptian",
      strInstructions:
        "Cook the lentils. Bring lentils and 4 cups of water to a boil in a medium pot or saucepan over high heat. Reduce the heat to low and cook until lentils are just tender (15-17 minutes). Drain from water and season with a little salt. (Note: when the lentils are ready, they should not be fully cooked. They should be only par-cooked and still have a bite to them as they need to finish cooking with the rice).\r\nNow, for the rice. Drain the rice from its soaking water. Combine the par-cooked lentils and the rice in the saucepan over medium-high heat with 1 tbsp cooking oil, salt, pepper, and coriander. Cook for 3 minutes, stirring regularly. Add warm water to cover the rice and lentil mixture by about 1 1/2 inches (you’ll probably use about 3 cups of water here). Bring to a boil; the water should reduce a bit. Now cover and cook until all the liquid has been absorbed and both the rice and lentils are well cooked through (about 20 minutes).  Keep covered and undisturbed for 5 minutes or so.\r\nNow make the pasta. While the rice and lentils are cooking, make the pasta according to package instructions by adding the elbow pasta to boiling water with a dash of salt and a little oil. Cook until the pasta is al dente. Drain.\r\nCover the chickpeas and warm in the microwave briefly before serving.\r\n\r\nMake the crispy onion topping. \r\n\r\nSprinkle the onion rings with salt, then toss them in the flour to coat. Shake off excess flour.\r\nIn a large skillet, heat the cooking oil over medium-high heat, cook the onion rings, stirring often, until they turn a nice caramelized brown. Onions must be crispy, but not burned (15-20 minutes).",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/4er7mj1598733193.jpg",
      strTags: "",
      strYoutube: "https://www.youtube.com/watch?v=y0d2ZMZBW4Y",
      strIngredient1: "Brown Lentils",
      strIngredient2: "Rice",
      strIngredient3: "Coriander",
      strIngredient4: "Macaroni",
      strIngredient5: "Chickpeas",
      strIngredient6: "Onion",
      strIngredient7: "Salt",
      strIngredient8: "Vegetable Oil",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "1 1/2 cups ",
      strMeasure2: "1 1/2 cups ",
      strMeasure3: "1/2 tsp",
      strMeasure4: "2 cups ",
      strMeasure5: "Can",
      strMeasure6: "1 large",
      strMeasure7: "Sprinking",
      strMeasure8: "1/2 cup ",
      strMeasure9: " ",
      strMeasure10: " ",
      strMeasure11: " ",
      strMeasure12: " ",
      strMeasure13: " ",
      strMeasure14: " ",
      strMeasure15: " ",
      strMeasure16: " ",
      strMeasure17: " ",
      strMeasure18: " ",
      strMeasure19: " ",
      strMeasure20: " ",
      strSource:
        "https://www.themediterraneandish.com/egyptian-koshari-recipe/",
      strImageSource: "",
      strCreativeCommonsConfirmed: "",
      dateModified: "",
    },
    {
      idMeal: "52769",
      strMeal: "Kapsalon",
      strDrinkAlternate: "",
      strCategory: "Lamb",
      strArea: "Dutch",
      strInstructions:
        "Cut the meat into strips. Heat oil in a pan and fry the strips for 6 minutes until it's ready.\r\nBake the fries until golden brown in a deep fryrer. When ready transfer to a backing dish. Make sure the fries are spread over the whole dish.\r\nCover the fries with a new layer of meat and spread evenly.\r\nAdd a layer of cheese over the meat. You can also use grated cheese. When done put in the oven for a few minutes until the cheese is melted.\r\nChop the lettuce, tomato and cucumber in small pieces and mix together. for a basic salad. As extra you can add olives jalapenos and a red union.\r\nDived the salad over the dish and Serve with garlicsauce and hot sauce",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/sxysrt1468240488.jpg",
      strTags: "Snack",
      strYoutube: "https://www.youtube.com/watch?v=UIcuiU1kV8I",
      strIngredient1: "Fries",
      strIngredient2: "Doner Meat",
      strIngredient3: "Garlic sauce",
      strIngredient4: "Hotsauce",
      strIngredient5: "Lettuce",
      strIngredient6: "Tomato",
      strIngredient7: "Cucumber",
      strIngredient8: "Gouda cheese",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "250 Grams",
      strMeasure2: "500 Grams",
      strMeasure3: "Topping",
      strMeasure4: "Topping",
      strMeasure5: "1 Bulb",
      strMeasure6: "1",
      strMeasure7: "3rd",
      strMeasure8: "100 Grams",
      strMeasure9: "",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
      strSource: "",
      strImageSource: "",
      strCreativeCommonsConfirmed: "",
      dateModified: "",
    },
    {
      idMeal: "52802",
      strMeal: "Fish pie",
      strDrinkAlternate: "",
      strCategory: "Seafood",
      strArea: "British",
      strInstructions:
        "01.Put the potatoes in a large pan of cold salted water and bring to the boil. Lower the heat, cover, then simmer gently for 15 minutes until tender. Drain, then return to the pan over a low heat for 30 seconds to drive off any excess water. Mash with 1 tbsp olive oil, then season.\r\n02.Meanwhile put the milk in a large sauté pan, add the fish and bring to the boil. Remove from the heat, cover and stand for 3 minutes. Remove the fish (reserving the milk) and pat dry with kitchen paper, then gently flake into an ovenproof dish, discarding the skin and any bones.\r\n03.Heat the remaining oil in a pan, stir in the flour and cook for 30 seconds. Gradually stir in 200-250ml of the reserved milk (discard the rest). Grate in nutmeg, season, then bubble until thick. Stir in the cream.\r\n04.Preheat the oven to 190°C/fan170°C/gas 5. Grate the artichokes and add to the dish with the leek, prawns and herbs. Stir the lemon zest and juice into the sauce, then pour over. Mix gently with a wooden spoon.\r\n05.Spoon the mash onto the fish mixture, then use a fork to make peaks, which will crisp and brown as it cooks. Sprinkle over the cheese, then bake for 35-40 minutes until golden and bubbling. Serve with wilted greens.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/ysxwuq1487323065.jpg",
      strTags: "Fish,Pie,Breakfast,Baking",
      strYoutube: "https://www.youtube.com/watch?v=2sX4fCgg-UI",
      strIngredient1: "Floury Potatoes",
      strIngredient2: "Olive Oil",
      strIngredient3: "Semi-skimmed Milk",
      strIngredient4: "White Fish Fillets",
      strIngredient5: "Plain flour",
      strIngredient6: "Nutmeg",
      strIngredient7: "Double Cream",
      strIngredient8: "Jerusalem Artichokes",
      strIngredient9: "Leek",
      strIngredient10: "Prawns",
      strIngredient11: "Parsley",
      strIngredient12: "Dill",
      strIngredient13: "Lemon",
      strIngredient14: "Gruyère",
      strIngredient15: "Lemon",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "900g",
      strMeasure2: "2 tbsp",
      strMeasure3: "600ml",
      strMeasure4: "800g",
      strMeasure5: "1 tbsp",
      strMeasure6: "Grating",
      strMeasure7: "3 tbsp",
      strMeasure8: "200g",
      strMeasure9: "1 finely sliced",
      strMeasure10: "200g peeled raw",
      strMeasure11: "Large handful",
      strMeasure12: "Handful",
      strMeasure13: "Grated zest of 1",
      strMeasure14: "25g grated",
      strMeasure15: "Juice of 1",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
      strSource: "",
      strImageSource: "",
      strCreativeCommonsConfirmed: "",
      dateModified: "",
    },
    {
      idMeal: "52854",
      strMeal: "Pancakes",
      strDrinkAlternate: "",
      strCategory: "Dessert",
      strArea: "American",
      strInstructions:
        "Put the flour, eggs, milk, 1 tbsp oil and a pinch of salt into a bowl or large jug, then whisk to a smooth batter. Set aside for 30 mins to rest if you have time, or start cooking straight away.\r\nSet a medium frying pan or crêpe pan over a medium heat and carefully wipe it with some oiled kitchen paper. When hot, cook your pancakes for 1 min on each side until golden, keeping them warm in a low oven as you go.\r\nServe with lemon wedges and sugar, or your favourite filling. Once cold, you can layer the pancakes between baking parchment, then wrap in cling film and freeze for up to 2 months.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/rwuyqx1511383174.jpg",
      strTags: "Breakfast,Desert,Sweet,Fruity",
      strYoutube: "https://www.youtube.com/watch?v=LWuuCndtJr0",
      strIngredient1: "Flour",
      strIngredient2: "Eggs",
      strIngredient3: "Milk",
      strIngredient4: "Sunflower Oil",
      strIngredient5: "Sugar",
      strIngredient6: "Raspberries",
      strIngredient7: "Blueberries",
      strIngredient8: "",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "100g ",
      strMeasure2: "2 large",
      strMeasure3: "300ml ",
      strMeasure4: "1 tbls",
      strMeasure5: "to serve",
      strMeasure6: "to serve",
      strMeasure7: "to serve",
      strMeasure8: "",
      strMeasure9: "",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
      strSource: "https://www.bbcgoodfood.com/recipes/2907669/easy-pancakes",
      strImageSource: "",
      strCreativeCommonsConfirmed: "",
      dateModified: "",
    },
    {
      idMeal: "52887",
      strMeal: "Kedgeree",
      strDrinkAlternate: "",
      strCategory: "Seafood",
      strArea: "British",
      strInstructions:
        "For the rice, heat the oil in a large, lidded pan, add the onion, then gently fry for 5 mins until softened but not coloured. Add the spices, season with salt, then continue to fry until the mix start to go brown and fragrant; about 3 mins.\r\nAdd the rice and stir in well. Add 600ml water, stir, then bring to the boil. Reduce to a simmer, then cover for 10 mins. Take off the heat and leave to stand, covered, for 10-15 mins more. The rice will be perfectly cooked if you do not lift the lid before the end of the cooking.\r\nMeanwhile, put the haddock and bay leaves in a frying pan, cover with the milk, then poach for 10 mins until the flesh flakes. Remove from the milk, peel away the skin, then flake the flesh into thumbsize pieces. Place the eggs in a pan, cover with water, bring to the boil, then reduce to a simmer. Leave for 4½-5 mins, plunge into cold water, then peel and cut the eggs into quarters. Gently mix the fish, eggs, parsley, coriander and rice together in the pan. Serve hot, sprinkled with a few extra herbs.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/utxqpt1511639216.jpg",
      strTags: "",
      strYoutube: "https://www.youtube.com/watch?v=_Pw1I1-SItE",
      strIngredient1: "Smoked Haddock",
      strIngredient2: "Bay Leaves",
      strIngredient3: "Milk",
      strIngredient4: "Eggs",
      strIngredient5: "Parsley",
      strIngredient6: "Coriander",
      strIngredient7: "Vegetable Oil",
      strIngredient8: "Onion",
      strIngredient9: "Coriander",
      strIngredient10: "Curry Powder",
      strIngredient11: "Rice",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "300g",
      strMeasure2: "2",
      strMeasure3: "300ml ",
      strMeasure4: "4",
      strMeasure5: "Handful",
      strMeasure6: "Handful",
      strMeasure7: "2 tbs",
      strMeasure8: "1 chopped",
      strMeasure9: "1 tsp ",
      strMeasure10: "2 tsp",
      strMeasure11: "300g",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
      strSource: "https://www.bbcgoodfood.com/recipes/10421/kedgeree",
      strImageSource: "",
      strCreativeCommonsConfirmed: "",
      dateModified: "",
    },
    {
      idMeal: "52906",
      strMeal: "Flamiche",
      strDrinkAlternate: "",
      strCategory: "Vegetarian",
      strArea: "French",
      strInstructions:
        "For the pastry, sift the flour and salt into the bowl of a food processor, add the butter and lard, then whizz together briefly until the mixture looks like fine breadcrumbs. Tip the mixture into a bowl, then stir in the cheese and enough of the water for the mixture to come together. Tip out onto a lightly floured surface and knead briefly until smooth. Roll out thinly and line a 23cm x 4cm loose-?bottomed fluted flan tin. Prick the base with a fork. Chill for 20 minutes.\r\n02.Melt the 75g butter in a saucepan over a low heat, then add the leeks and the salt. Cover and cook for ?10 minutes until soft. Uncover the pan, increase the heat and cook ?for 2 minutes, stirring occasionally, until the liquid has evaporated. Spoon onto a plate and leave to cool.\r\n03.Preheat the oven to 200°C/fan180°C/gas 6. Line the pastry case with baking paper and baking beans or rice and blind bake for 15-20 minutes until the edges are biscuit-coloured. Remove the paper and beans/rice and return the case to the oven for 7-10 minutes until the base is crisp and lightly golden. Remove and set aside. Reduce the oven temperature to 190°C/fan170°C/gas 5.\r\n04.Put the crème fraîche into a bowl with the whole egg, egg yolks and nutmeg. Lightly beat together, then season. Stir in the leeks. Spoon ?the mixture into the tart case and bake for 35-40 minutes until set ?and lightly golden. Remove from ?the oven and leave for 10 minutes. Take out of the tin and serve.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/wssvvs1511785879.jpg",
      strTags: "Tart",
      strYoutube: "https://www.youtube.com/watch?v=vT0q5c880Rg",
      strIngredient1: "Butter",
      strIngredient2: "Leek",
      strIngredient3: "Salt",
      strIngredient4: "Creme Fraiche",
      strIngredient5: "Egg",
      strIngredient6: "Egg Yolks",
      strIngredient7: "Nutmeg",
      strIngredient8: "Plain Flour",
      strIngredient9: "Salt",
      strIngredient10: "Butter",
      strIngredient11: "Lard",
      strIngredient12: "Cheddar Cheese",
      strIngredient13: "Water",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "75g",
      strMeasure2: "1kg",
      strMeasure3: "½ tsp",
      strMeasure4: "300ml ",
      strMeasure5: "1",
      strMeasure6: "3",
      strMeasure7: "¼ teaspoon",
      strMeasure8: "225g",
      strMeasure9: "½ tsp",
      strMeasure10: "60g",
      strMeasure11: "60g",
      strMeasure12: "50g",
      strMeasure13: "2 tbs",
      strMeasure14: "",
      strMeasure15: "",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
      strSource:
        "http://www.deliciousmagazine.co.uk/recipes/flamiche-flemish-leek-tart/",
      strImageSource: "",
      strCreativeCommonsConfirmed: "",
      dateModified: "",
    },
    {
      idMeal: "52980",
      strMeal: "Stamppot",
      strDrinkAlternate: "",
      strCategory: "Pork",
      strArea: "Dutch",
      strInstructions:
        "\r\nWash and peel the potatoes and cut into similarly sized pieces for even cooking.\r\n\r\nIn a large soup pot, boil the potatoes and the bay leaves in salted water for 20 minutes. Discard the bay leaves.\r\n\r\nIf you're not using a bag of ready-cut curly kale, wash the bunches thoroughly under cool running water to get rid of all soil—you wouldn't want that gritty texture in your finished dish. Trim any coarse stems and discard any brown leaves. With a sharp knife, cut the curly kale into thin strips.\r\n\r\nPeel and chop the shallots.\r\n\r\nIn a frying pan or skillet, melt 1 tbsp. of butter and saute the shallots for a few minutes before adding the curly kale and 2 tbsp. of water. Season and cook for about 10 minutes, or until tender.\r\n\r\nWarm the milk on the stove or in the microwave.\r\n\r\nDrain, shake and dry the potatoes with kitchen towels before mashing with a potato masher or ricer. Working quickly, add the warm milk and the remaining butter. Season to taste with nutmeg, salt, and pepper. \r\n\r\nMix the cooked curly kale through the cooked mashed potato mixture.\r\n\r\nTop with slices of the smoked sausage and serve hot with your favorite mustard or gravy.\r\n\r\nServe and enjoy!",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/hyarod1565090529.jpg",
      strTags: "Savory,Breakfast",
      strYoutube: "https://www.youtube.com/watch?v=hTrSXryX31A",
      strIngredient1: "Potatoes",
      strIngredient2: "Bay Leaf",
      strIngredient3: "Shallots",
      strIngredient4: "Butter",
      strIngredient5: "Kale",
      strIngredient6: "Sausages",
      strIngredient7: "Milk",
      strIngredient8: "Nutmeg",
      strIngredient9: "Salt",
      strIngredient10: "Pepper",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "1.5kg",
      strMeasure2: "2 leaves",
      strMeasure3: "2",
      strMeasure4: "3 tbs",
      strMeasure5: "750g",
      strMeasure6: "2",
      strMeasure7: "500ml",
      strMeasure8: "Grated",
      strMeasure9: "Pinch",
      strMeasure10: "Pinch",
      strMeasure11: " ",
      strMeasure12: " ",
      strMeasure13: " ",
      strMeasure14: " ",
      strMeasure15: " ",
      strMeasure16: " ",
      strMeasure17: " ",
      strMeasure18: " ",
      strMeasure19: " ",
      strMeasure20: " ",
      strSource:
        "https://www.thespruceeats.com/stamppot-with-curly-kale-and-rookworst-1128837",
      strImageSource: "",
      strCreativeCommonsConfirmed: "",
      dateModified: "",
    },
    {
      idMeal: "53006",
      strMeal: "Moussaka",
      strDrinkAlternate: "",
      strCategory: "Beef",
      strArea: "Greek",
      strInstructions:
        "Heat the grill to high. Brown the beef in a deep ovenproof frying pan over a high heat for 5 mins. Meanwhile, prick the aubergine with a fork, then microwave on High for 3-5 mins until soft. Mix the yogurt, egg and parmesan together, then add a little seasoning.\r\n\r\nStir the tomatoes, purée and potatoes in with the beef with some seasoning and heat through. Smooth the surface of the beef mixture with the back of a spoon, then slice the cooked aubergine and arrange on top. Pour the yogurt mixture over the aubergines, smooth out evenly, then grill until the topping has set and turned golden.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/ctg8jd1585563097.jpg",
      strTags: "",
      strYoutube: "https://www.youtube.com/watch?v=8U_29i9Qp5U",
      strIngredient1: "Beef",
      strIngredient2: "Aubergine",
      strIngredient3: "Greek Yogurt",
      strIngredient4: "Egg",
      strIngredient5: "Parmesan",
      strIngredient6: "Tomato",
      strIngredient7: "Tomato Puree",
      strIngredient8: "Potatoes",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "500g",
      strMeasure2: "1 large",
      strMeasure3: "150g",
      strMeasure4: "1 beaten",
      strMeasure5: "3 tbs",
      strMeasure6: "400g",
      strMeasure7: "4 tbs",
      strMeasure8: "350g",
      strMeasure9: " ",
      strMeasure10: " ",
      strMeasure11: " ",
      strMeasure12: " ",
      strMeasure13: " ",
      strMeasure14: " ",
      strMeasure15: " ",
      strMeasure16: " ",
      strMeasure17: " ",
      strMeasure18: " ",
      strMeasure19: " ",
      strMeasure20: " ",
      strSource: "https://www.bbcgoodfood.com/recipes/must-make-moussaka",
      strImageSource: "",
      strCreativeCommonsConfirmed: "",
      dateModified: "",
    },
    {
      idMeal: "53028",
      strMeal: "Shawarma",
      strDrinkAlternate: "",
      strCategory: "Chicken",
      strArea: "Egyptian",
      strInstructions:
        "Combine the marinade ingredients in a large ziplock bag (or bowl).\r\nAdd the chicken and use your hands to make sure each piece is coated. If using a ziplock bag, I find it convenient to close the bag then massage the bag to disperse the rub all over each chicken piece.\r\nMarinate overnight or up to 24 hours.\r\nCombine the Yoghurt Sauce ingredients in a bowl and mix. Cover and put in the fridge until required (it will last for 3 days in the fridge).\r\nHeat grill/BBQ (or large heavy based pan on stove) on medium high. You should not need to oil it because the marinade has oil in it and also thigh fillets have fat. But if you are worried then oil your hotplate/grill. (See notes for baking)\r\nPlace chicken on the grill and cook the first side for 4 to 5 minutes until nicely charred, then turn and cook the other side for 3 to 4 minutes (the 2nd side takes less time).\r\nRemove chicken from the grill and cover loosely with foil. Set aside to rest for 5 minutes.\r\nTO SERVE\r\nSlice chicken and pile onto platter alongside flatbreads, Salad and the Yoghurt Sauce.\r\nTo make a wrap, get a piece of flatbread and smear with Yoghurt Sauce. Top with a bit of lettuce and tomato and Chicken Shawarma. Roll up and enjoy!",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/kcv6hj1598733479.jpg",
      strTags: "",
      strYoutube: "https://www.youtube.com/watch?v=3lxUIeKDgic",
      strIngredient1: "Chicken Thighs",
      strIngredient2: "Coriander",
      strIngredient3: "Cumin",
      strIngredient4: "Cardamom",
      strIngredient5: "Cayenne Pepper",
      strIngredient6: "Paprika",
      strIngredient7: "Lemon Juice",
      strIngredient8: "Olive Oil",
      strIngredient9: "Greek Yogurt",
      strIngredient10: "Garlic Clove",
      strIngredient11: "Cumin",
      strIngredient12: "Lemon Juice",
      strIngredient13: "Lettuce",
      strIngredient14: "Tomato",
      strIngredient15: "Pita Bread",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "1 kg",
      strMeasure2: "1 tbs",
      strMeasure3: "1 tbs",
      strMeasure4: "1 tbs",
      strMeasure5: "1 tsp ",
      strMeasure6: "2 tsp",
      strMeasure7: "2 tbs",
      strMeasure8: "3 tbs",
      strMeasure9: "1 cup ",
      strMeasure10: "1",
      strMeasure11: "1 tsp ",
      strMeasure12: "Splash",
      strMeasure13: "Sliced",
      strMeasure14: "Sliced",
      strMeasure15: "6",
      strMeasure16: " ",
      strMeasure17: " ",
      strMeasure18: " ",
      strMeasure19: " ",
      strMeasure20: " ",
      strSource:
        "https://www.recipetineats.com/chicken-sharwama-middle-eastern/",
      strImageSource: "",
      strCreativeCommonsConfirmed: "",
      dateModified: "",
    },
    {
      idMeal: "52791",
      strMeal: "Eton Mess",
      strDrinkAlternate: "",
      strCategory: "Dessert",
      strArea: "British",
      strInstructions:
        "Purée half the strawberries in a blender. Chop the remaining strawberries, reserving four for decoration.\r\nWhip the double cream until stiff peaks form, then fold in the strawberry purée and crushed meringue. Fold in the chopped strawberries and ginger cordial, if using.\r\nSpoon equal amounts of the mixture into four cold wine glasses. Serve garnished with the remaining strawberries and a sprig of mint.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/uuxwvq1483907861.jpg",
      strTags: "Dairy,Fruity,Desert,Treat,Speciality",
      strYoutube: "https://www.youtube.com/watch?v=43WgiNq54L8",
      strIngredient1: "strawberries",
      strIngredient2: "double cream",
      strIngredient3: "meringue nests",
      strIngredient4: "ginger cordial",
      strIngredient5: "Mint",
      strIngredient6: "",
      strIngredient7: "",
      strIngredient8: "",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "500g",
      strMeasure2: "400ml",
      strMeasure3: "3 x 7.5cm",
      strMeasure4: "1 tbsp",
      strMeasure5: "sprigs of fresh",
      strMeasure6: "",
      strMeasure7: "",
      strMeasure8: "",
      strMeasure9: "",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
      strSource: "",
      strImageSource: "",
      strCreativeCommonsConfirmed: "",
      dateModified: "",
    },
    {
      idMeal: "52811",
      strMeal: "Ribollita",
      strDrinkAlternate: "",
      strCategory: "Vegetarian",
      strArea: "Italian",
      strInstructions:
        "Put 2 tablespoons of the oil in a large pot over medium heat. When it’s hot, add onion, carrot, celery and garlic; sprinkle with salt and pepper and cook, stirring occasionally, until vegetables are soft, 5 to 10 minutes.\r\nHeat the oven to 500 degrees. Drain the beans; if they’re canned, rinse them as well. Add them to the pot along with tomatoes and their juices and stock, rosemary and thyme. Bring to a boil, then reduce heat so the soup bubbles steadily; cover and cook, stirring once or twice to break up the tomatoes, until the flavors meld, 15 to 20 minutes.\r\nFish out and discard rosemary and thyme stems, if you like, and stir in kale. Taste and adjust seasoning. Lay bread slices on top of the stew so they cover the top and overlap as little as possible. Scatter red onion slices over the top, drizzle with the remaining 3 tablespoons oil and sprinkle with Parmesan.\r\nPut the pot in the oven and bake until the bread, onions and cheese are browned and crisp, 10 to 15 minutes. (If your pot fits under the broiler, you can also brown the top there.) Divide the soup and bread among 4 bowls and serve.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/xrrwpx1487347049.jpg",
      strTags: "Vegetarian",
      strYoutube: "https://www.youtube.com/watch?v=BiQUYTBb6eQ",
      strIngredient1: "Olive Oil",
      strIngredient2: "Onion",
      strIngredient3: "Carrot",
      strIngredient4: "Celery",
      strIngredient5: "Garlic",
      strIngredient6: "Cannellini Beans",
      strIngredient7: "Canned tomatoes",
      strIngredient8: "Water",
      strIngredient9: "Rosemary",
      strIngredient10: "Thyme",
      strIngredient11: "Kale",
      strIngredient12: "Wholegrain Bread",
      strIngredient13: "Red Onion",
      strIngredient14: "Parmesan",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "5 tablespoons",
      strMeasure2: "1 chopped",
      strMeasure3: "1 chopped",
      strMeasure4: "1 stalk chopped",
      strMeasure5: "1 tablespoon minced",
      strMeasure6: "2 cups",
      strMeasure7: "1",
      strMeasure8: "4 cups",
      strMeasure9: "1 fresh sprig",
      strMeasure10: "1 fresh sprig",
      strMeasure11: "1 pound chopped",
      strMeasure12: "4 thick slices",
      strMeasure13: "1 thinly sliced",
      strMeasure14: "½ cup freshly grated",
      strMeasure15: "",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
      strSource: "https://cooking.nytimes.com/recipes/1016052-ribollita",
      strImageSource: "",
      strCreativeCommonsConfirmed: "",
      dateModified: "",
    },
    {
      idMeal: "52871",
      strMeal: "Yaki Udon",
      strDrinkAlternate: "",
      strCategory: "Vegetarian",
      strArea: "Japanese",
      strInstructions:
        "Boil some water in a large saucepan. Add 250ml cold water and the udon noodles. (As they are so thick, adding cold water helps them to cook a little bit slower so the middle cooks through). If using frozen or fresh noodles, cook for 2 mins or until al dente; dried will take longer, about 5-6 mins. Drain and leave in the colander.\r\nHeat 1 tbsp of the oil, add the onion and cabbage and sauté for 5 mins until softened. Add the mushrooms and some spring onions, and sauté for 1 more min. Pour in the remaining sesame oil and the noodles. If using cold noodles, let them heat through before adding the ingredients for the sauce – otherwise tip in straight away and keep stir-frying until sticky and piping hot. Sprinkle with the remaining spring onions.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/wrustq1511475474.jpg",
      strTags: "LowCalorie",
      strYoutube: "https://www.youtube.com/watch?v=5Iy0MCowSvA",
      strIngredient1: "Udon Noodles",
      strIngredient2: "Sesame Seed Oil",
      strIngredient3: "Onion",
      strIngredient4: "Cabbage",
      strIngredient5: "Shiitake Mushrooms",
      strIngredient6: "Spring Onions",
      strIngredient7: "Mirin",
      strIngredient8: "Soy Sauce",
      strIngredient9: "Caster Sugar",
      strIngredient10: "Worcestershire Sauce",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "250g",
      strMeasure2: "2 tbs",
      strMeasure3: "1 sliced",
      strMeasure4: "0.25",
      strMeasure5: "10",
      strMeasure6: "4",
      strMeasure7: "4 tbsp",
      strMeasure8: "2 tbs",
      strMeasure9: "1 tblsp ",
      strMeasure10: "1 tblsp ",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
      strSource: "https://www.bbcgoodfood.com/recipes/yaki-udon",
      strImageSource: "",
      strCreativeCommonsConfirmed: "",
      dateModified: "",
    },
    {
      idMeal: "52926",
      strMeal: "Tourtiere",
      strDrinkAlternate: "",
      strCategory: "Pork",
      strArea: "Canadian",
      strInstructions:
        "Heat oven to 200C/180C fan/gas 6. Boil the potato until tender, drain and mash, then leave to cool. Heat the oil in a non-stick pan, add the mince and onion and quickly fry until browned. Add the garlic, spices, stock, plenty of pepper and a little salt and mix well. Remove from the heat, stir into the potato and leave to cool.\r\nRoll out half the pastry and line the base of a 20-23cm pie plate or flan tin. Fill with the pork mixture and brush the edges of the pastry with water. Roll out the remaining dough and cover the pie. Press the edges of the pastry to seal, trimming off the excess. Prick the top of the pastry case to allow steam to escape and glaze the top with the beaten egg.\r\nBake for 30 mins until the pastry is crisp and golden. Serve cut into wedges with a crisp green salad. Leftovers are good cold for lunch the next day, served with a selection of pickles.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/ytpstt1511814614.jpg",
      strTags: "Pie,MainMeal,BBQ,Cake",
      strYoutube: "https://www.youtube.com/watch?v=A96hbwobKKs",
      strIngredient1: "Potatoes",
      strIngredient2: "Sunflower Oil",
      strIngredient3: "Minced Pork",
      strIngredient4: "Onion",
      strIngredient5: "Garlic Clove",
      strIngredient6: "Cinnamon",
      strIngredient7: "Allspice",
      strIngredient8: "Nutmeg",
      strIngredient9: "Vegetable Stock",
      strIngredient10: "Shortcrust Pastry",
      strIngredient11: "Egg",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "1 medium",
      strMeasure2: "1 tsp ",
      strMeasure3: "500g",
      strMeasure4: "1 finely chopped ",
      strMeasure5: "1 finely chopped ",
      strMeasure6: "¼ tsp",
      strMeasure7: "¼ tsp",
      strMeasure8: "¼ tsp",
      strMeasure9: "100ml",
      strMeasure10: "400g",
      strMeasure11: "To Glaze",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
      strSource:
        "https://www.bbcgoodfood.com/recipes/531644/spiced-pork-and-potato-pie",
      strImageSource: "",
      strCreativeCommonsConfirmed: "",
      dateModified: "",
    },
  ],
};

export const mealsExample = [
  {
    id: "1",
    title: "Creamy Tomato Soup",
    youtube: "https://www.youtube.com/watch?v=lBhwjjUiFk4",
    source: "https://www.bbcgoodfood.com/recipes/2604646/creamy-tomato-soup",
    thumbImg:
      "https://www.themealdb.com/images/media/meals/stpuws1511191310.jpg",
    instructions:
      "Put the oil, onions, celery, carrots, potatoes and bay leaves in a big casserole dish, or two saucepans. Fry gently until the onions are softened – about 10-15 mins. Fill the kettle and boil it.\r\nStir in the tomato purée, sugar, vinegar, chopped tomatoes and passata, then crumble in the stock cubes. Add 1 litre boiling water and bring to a simmer. Cover and simmer for 15 mins until the potato is tender, then remove the bay leaves. Purée with a stick blender (or ladle into a blender in batches) until very smooth. Season to taste and add a pinch more sugar if it needs it. The soup can now be cooled and chilled for up to 2 days, or frozen for up to 3 months.\r\nTo serve, reheat the soup, stirring in the milk – try not to let it boil. Serve in small bowls with cheesy sausage rolls.",
    ingredients: [
      { name: "Olive Oil", measure: "3 tbsp" },
      { name: "Onions", measure: "2 chopped" },
      { name: "Celery", measure: "2 sticks" },
      { name: "Carrots", measure: "300g" },
      { name: "Potatoes", measure: "500g" },
      { name: "Bay Leaf", measure: "4" },
      { name: "Tomato Puree", measure: "5 tblsp " },
      { name: "Sugar", measure: "2 tblsp " },
      { name: "White Vinegar", measure: "2 tblsp " },
      { name: "Chopped Tomatoes", measure: "1½ kg" },
      { name: "Passata", measure: "500g" },
      { name: "Vegetable Stock Cube", measure: "3" },
      { name: "Whole Milk", measure: "400ml" },
      { name: "", measure: "" },
      { name: "", measure: "" },
      { name: "", measure: "" },
      { name: "", measure: "" },
      { name: "", measure: "" },
      { name: "", measure: "" },
      { name: "", measure: "" },
      {},
    ],
  },
  {
    id: "2",
    title: "Stuffed Lamb Tomatoes",
    youtube: "https://www.youtube.com/watch?v=KfJp-QfrCz4",
    source:
      "https://www.bbcgoodfood.com/recipes/stuffed-tomatoes-lamb-mince-dill-rice",
    thumbImg:
      "https://www.themealdb.com/images/media/meals/u55lbp1585564013.jpg",
    instructions:
      "Heat oven to 180C/160C fan/gas 4. Slice the tops off the tomatoes and reserve. Scoop out most of the pulp with a teaspoon, being careful not to break the skin. Finely chop the pulp, and keep any juices. Sprinkle the insides of the tomatoes with a little sugar to take away the acidity, then place them on a baking tray.\r\n\r\nHeat 2 tbsp olive oil in a large frying pan, add the onion and garlic, then gently cook for about 10 mins until soft but not coloured. Add the lamb, cinnamon and tomato purée, turn up the heat, then fry until the meat is browned. Add the tomato pulp and juice, the rice and the stock. Season generously. Bring to the boil, then simmer for 15 mins or until the rice is tender and the liquid has been absorbed. Set aside to cool a little, then stir in the herbs.\r\n\r\nStuff the tomatoes up to the brim, top tomatoes with their lids, drizzle with 2 tbsp more olive oil, sprinkle 3 tbsp water into the tray, then bake for 35 mins. Serve with salad and crusty bread, hot or cold.",
    ingredients: [
      { name: "Tomatoes", measure: "4 large" },
      { name: "Sugar", measure: "Pinch" },
      { name: "Olive Oil", measure: "4 tbs" },
      { name: "Onion", measure: "1 chopped" },
      { name: "Garlic Clove", measure: "2 finely chopped" },
      { name: "Lamb", measure: "200g" },
      { name: "Cinnamon", measure: "1 tbs" },
      { name: "Tomato Puree", measure: "2 tbs chopped" },
      { name: "Rice", measure: "50g" },
      { name: "Chicken Stock", measure: "100ml" },
      { name: "Dill", measure: "4 tbs" },
      { name: "Chopped Parsley", measure: "2 tbs" },
      { name: "Mint", measure: "1 tbs" },
      { name: "", measure: " " },
      { name: "", measure: " " },
      { name: "", measure: " " },
      { name: "", measure: " " },
      { name: "", measure: " " },
      { name: "", measure: " " },
      { name: "", measure: " " },
      {},
    ],
  },
  {
    id: "3",
    title: "Lamb tomato and sweet spices",
    youtube: "https://www.youtube.com/watch?v=vaZb1MnFBgA",
    source:
      "http://www.ottolenghi.co.uk/recipes/meat/lamb-tomato-and-sweet-spices-shop",
    thumbImg:
      "https://www.themealdb.com/images/media/meals/qtwtss1468572261.jpg",
    instructions:
      "Use pickled vine leaves here, preserved in brine. Small delicate leaves are better than the large bristly ones but, if only large leaves are to hand, then trim them to roughly 12 by 12 cms so that you don't get too many layers of leaves around the filling. And remove any stalks. Drain the preserved leaves, immerse them in boiling water for 10 minutes and then leave to dry on a tea towel before use. \r\nBasmati rice with butter and pine nuts is an ideal accompaniment. Couscous is great, too. Serves four.\r\nFirst make the filling. Put all the ingredients, apart from the tomatoes, in a bowl. Cut the tomatoes in half, coarsely grate into the bowl and discard the skins. Add half a teaspoon of salt and some black pepper, and stir. Leave on the side, or in the fridge, for up to a day. Before using, gently squeeze with your hands and drain away any juices that come out.\r\nTo make the sauce, heat the oil in a medium pan. Add the ginger and garlic, cook for a minute or two, taking care not to burn them, then add the tomato, lemon juice and sugar. Season, and simmer for 20 minutes.\r\nWhile the sauce is bubbling away, prepare the vine leaves. Use any torn or broken leaves to line the base of a wide, heavy saucepan. Trim any leaves from the fennel, cut it vertically into 0.5cm-thick slices and spread over the base of the pan to cover completely.\r\nLay a prepared vine leaf (see intro) on a work surface, veiny side up. Put two teaspoons of filling at the base of the leaf in a 2cm-long by 1cm-wide strip. Fold the sides of the leaf over the filling, then roll it tightly from bottom to top, in a cigar shape. Place in the pan, seam down, and repeat with the remaining leaves, placing them tightly next to each other in lines or circles (in two layers if necessary).\r\nPour the sauce over the leaves (and, if needed, add water just to cover). Place a plate on top, to weigh the leaves down, then cover with a lid. Bring to a boil, reduce the heat and cook on a bare simmer for 70 minutes. Most of the liquid should evaporate. Remove from the heat, and leave to cool a little - they are best served warm. When serving, bring to the table in the pan - it looks great. Serve a few vine leaves and fennel slices with warm rice. Spoon the braising juices on top and garnish with coriander.",
    ingredients: [
      { name: "olive oil", measure: "2 tbsp" },
      { name: "ginger", measure: "4cm piece finely chopped" },
      { name: "garlic", measure: "2 cloves peeled and chopped" },
      { name: "tomatoes", measure: "800g peeled and chopped " },
      { name: "lemon juice", measure: "2 tbsp" },
      { name: "caster sugar", measure: "1 tsp" },
      { name: "vine leaves", measure: "50" },
      { name: "fennel bulb", measure: "1 large" },
      { name: "lamb mince", measure: "400g" },
      { name: "onion", measure: "1 medium" },
      { name: "potato", measure: "1 small peeled and coarsely grated" },
      { name: "basmati rice", measure: "2 tbsp" },
      { name: "chopped parsley", measure: "2 tbsp" },
      { name: "coriander", measure: "2 tbsp chopped" },
      { name: "lemon juice", measure: "1 tbsp" },
      { name: "garlic", measure: "2 cloves" },
      { name: "clove", measure: "½ tsp ground" },
      { name: "cinnamon", measure: "½ tsp ground " },
      { name: "tomatoes", measure: "2 medium" },
      { name: "", measure: "" },
      {},
    ],
  },
  {
    id: "4",
    title: "Baked salmon with fennel & tomatoes",
    youtube: "https://www.youtube.com/watch?v=xvPR2Tfw5k0",
    source:
      "https://www.bbcgoodfood.com/recipes/7745/baked-salmon-with-fennel-and-tomatoes",
    thumbImg: "https://www.themealdb.com/images/media/meals/1548772327.jpg",
    instructions:
      "Heat oven to 180C/fan 160C/gas 4. Trim the fronds from the fennel and set aside. Cut the fennel bulbs in half, then cut each half into 3 wedges. Cook in boiling salted water for 10 mins, then drain well. Chop the fennel fronds roughly, then mix with the parsley and lemon zest.\r\n\r\nSpread the drained fennel over a shallow ovenproof dish, then add the tomatoes. Drizzle with olive oil, then bake for 10 mins. Nestle the salmon among the veg, sprinkle with lemon juice, then bake 15 mins more until the fish is just cooked. Scatter over the parsley and serve.",
    ingredients: [
      { name: "Fennel", measure: "2 medium" },
      { name: "Parsley", measure: "2 tbs chopped" },
      { name: "Lemon", measure: "Juice of 1" },
      { name: "Cherry Tomatoes", measure: "175g" },
      { name: "Olive Oil", measure: "1 tbs" },
      { name: "Salmon", measure: "350g" },
      { name: "Black Olives", measure: "to serve" },
      { name: "", measure: "" },
      { name: "", measure: "" },
      { name: "", measure: "" },
      { name: "", measure: "" },
      { name: "", measure: "" },
      { name: "", measure: "" },
      { name: "", measure: "" },
      { name: "", measure: "" },
      { name: "", measure: "" },
      { name: "", measure: "" },
      { name: "", measure: "" },
      { name: "", measure: "" },
      { name: "", measure: "" },
      {},
    ],
  },
  {
    id: "5",
    title: "Chilli prawn linguine",
    thumbImg:
      "https://www.themealdb.com/images/media/meals/usywpp1511189717.jpg",
    ingredients: [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ],
  },
  {
    id: "6",
    title: "Chivito uruguayo",
    thumbImg:
      "https://www.themealdb.com/images/media/meals/n7qnkb1630444129.jpg",
    ingredients: [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ],
  },
  {
    id: "7",
    title: "Kapsalon",
    thumbImg:
      "https://www.themealdb.com/images/media/meals/sxysrt1468240488.jpg",
    ingredients: [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ],
  },
  {
    id: "8",
    title: "Turkey Meatloaf",
    youtube: "https://www.youtube.com/watch?v=mTvlmY4vCug",
    source: "https://www.bbcgoodfood.com/recipes/turkey-meatloaf",
    thumbImg:
      "https://www.themealdb.com/images/media/meals/ypuxtw1511297463.jpg",
    instructions:
      "Heat oven to 180C/160C fan/gas 4. Heat the oil in a large frying pan and cook the onion for 8-10 mins until softened. Add the garlic, Worcestershire sauce and 2 tsp tomato purée, and stir until combined. Set aside to cool.\r\n\r\nPut the turkey mince, egg, breadcrumbs and cooled onion mix in a large bowl and season well. Mix everything to combine, then shape into a rectangular loaf and place in a large roasting tin. Spread 2 tbsp barbecue sauce over the meatloaf and bake for 30 mins.\r\n\r\nMeanwhile, drain 1 can of beans only, then pour both cans into a large bowl. Add the remaining barbecue sauce and tomato purée. Season and set aside.\r\n\r\nWhen the meatloaf has had its initial cooking time, scatter the beans around the outside and bake for 15 mins more until the meatloaf is cooked through and the beans are piping hot. Scatter over the parsley and serve the meatloaf in slices.",
    ingredients: [
      { name: "Olive Oil", measure: "1 tblsp " },
      { name: "Onion", measure: "1 large" },
      { name: "Garlic", measure: "1 clove peeled crushed" },
      { name: "Worcestershire Sauce", measure: "2 tblsp " },
      { name: "Tomato Puree", measure: "3 tsp" },
      { name: "Turkey Mince", measure: "500g" },
      { name: "Eggs", measure: "1 large" },
      { name: "Breadcrumbs", measure: "85g" },
      { name: "Barbeque Sauce", measure: "2 tblsp " },
      { name: "Cannellini Beans", measure: "800g" },
      { name: "Parsley", measure: "2 tblsp " },
      { name: "", measure: "" },
      { name: "", measure: "" },
      { name: "", measure: "" },
      { name: "", measure: "" },
      { name: "", measure: "" },
      { name: "", measure: "" },
      { name: "", measure: "" },
      { name: "", measure: "" },
      { name: "", measure: "" },
      {},
    ],
  },
  {
    id: "9",
    title: "Montreal Smoked Meat",
    youtube: "https://www.youtube.com/watch?v=g5oCDoyxbBk",
    source: "http://www.meatwave.com/blog/montreal-smoked-meat-recipe",
    thumbImg:
      "https://www.themealdb.com/images/media/meals/uttupv1511815050.jpg",
    instructions:
      "To make the cure, in a small bowl mix together salt, pink salt, black pepper, coriander, sugar, bay leaf, and cloves. Coat entire brisket with the cure and place in an extra-large resealable plastic bag. Place in the coldest part of the refrigerator and cure for 4 days, flipping brisket twice a day.\r\nRemove brisket from bag and wash as much cure off as possible under cold running water. Place brisket in a large container and fill with water and let soak for 2 hours, replacing water every 30 minutes. Remove from water and pat dry with paper towels.\r\nTo make the rub, mix together black pepper, coriander, paprika, garlic powder, onion powder, dill weed, mustard, celery seed, and crushed red papper in a small bowl. Coat entire brisket with the rub.\r\nFire up smoker or grill to 225 degrees, adding chunks of smoking wood chunks when at temperature. When wood is ignited and producing smoke, place brisket in, fat side up, and smoke until an instant read thermometer registers 165 degrees when inserted into thickest part of the brisket, about 6 hours.\r\nTransfer brisket to large roasting pan with V-rack. Place roasting pan over two burners on stovetop and fill with 1-inch of water. Bring water to a boil over high heat, reduce heat to medium, cover roasting pan with aluminum foil, and steam brisket until an instant read thermometer registers 180 degrees when inserted into thickest part of the meat, 1 to 2 hours, adding more hot water as needed.\r\nTransfer brisket to cutting board and let cool slightly. Slice and serve, preferably on rye with mustard.",
    ingredients: [
      { name: "Beef Brisket", measure: "1" },
      { name: "Salt", measure: "3 tbs" },
      { name: "Black Pepper", measure: "3 tbs" },
      { name: "Coriander", measure: "1 tbs" },
      { name: "Sugar", measure: "1 tbs" },
      { name: "Bay Leaf", measure: "1 tsp " },
      { name: "Cloves", measure: "1 tsp " },
      { name: "Black Pepper", measure: "3 tbs" },
      { name: "Coriander", measure: "1 tbs" },
      { name: "Paprika", measure: "1 tbs" },
      { name: "Garlic", measure: "1 tbs" },
      { name: "Onion", measure: "1 tbs" },
      { name: "Dill", measure: "1 tbs" },
      { name: "English Mustard", measure: "1 tsp " },
      { name: "Celery Salt", measure: "1 tbs" },
      { name: "Red Pepper Flakes", measure: "1 tsp " },
      { name: "", measure: "" },
      { name: "", measure: "" },
      { name: "", measure: "" },
      { name: "", measure: "" },
      {},
    ],
  },
  {
    id: "10",
    title: "Bitterballen (Dutch meatballs)",
    youtube: "https://www.youtube.com/watch?v=q8AKfYUtDuM",
    source:
      "https://www.holland.com/global/tourism/information/traditional-dutch-food/bitterballen.htm",
    thumbImg:
      "https://www.themealdb.com/images/media/meals/lhqev81565090111.jpg",
    instructions:
      "Melt the butter in a skillet or pan. When melted, add the flour little by little and stir into a thick paste. Slowly stir in the stock, making sure the roux absorbs the liquid. Simmer for a couple of minutes on a low heat while you stir in the onion, parsley and the shredded meat. The mixture should thicken and turn into a heavy, thick sauce.\r\n\r\nPour the mixture into a shallow container, cover and refrigerate for several hours, or until the sauce has solidified.\r\n\r\nTake a heaping tablespoon of the cold, thick sauce and quickly roll it into a small ball. Roll lightly through the flour, then the egg and finally the breadcrumbs. Make sure that the egg covers the whole surface of the bitterbal. When done, refrigerate the snacks while the oil in your fryer heats up to 190C (375F). Fry four bitterballen at a time, until golden.\r\n\r\nServe on a plate with a nice grainy or spicy mustard. \r\n",
    ingredients: [
      { name: "Butter", measure: "100g " },
      { name: "Flour", measure: "150g" },
      { name: "Beef Stock", measure: "700ml" },
      { name: "Onion", measure: "30g" },
      { name: "Parsley", measure: "1 tbs" },
      { name: "Beef", measure: "400g" },
      { name: "Salt", measure: "Pinch" },
      { name: "Pepper", measure: "Pinch" },
      { name: "Nutmeg", measure: "Pinch" },
      { name: "Flour", measure: "50g" },
      { name: "Eggs", measure: "2 Beaten " },
      { name: "Breadcrumbs", measure: "50g" },
      { name: "", measure: " " },
      { name: "", measure: " " },
      { name: "", measure: " " },
      { name: "", measure: " " },
      { name: "", measure: " " },
      { name: "", measure: " " },
      { name: "", measure: " " },
      { name: "", measure: " " },
      {},
    ],
  },
  {
    id: "11",
    title:
      "Soy-Glazed Meatloaves with Wasabi Mashed Potatoes & Roasted Carrots",
    youtube: "",
    source: "",
    thumbImg:
      "https://www.themealdb.com/images/media/meals/o2wb6p1581005243.jpg",
    instructions:
      "1. Preheat oven to 425 degrees. Wash and dry all produce. Dice potatoes into 1/2-inch pieces. Trim, peel, and cut carrots on a diagonal into 1/2-inch-thick pieces. Trim and thinly slice scallions, separating whites from greens; finely chop whites. Peel and finely chop garlic.\r\n\r\n2. In a medium bowl, soak bread with 2 TBSP water (4 TBSP for 4 servings); break up with your hands until pasty. Stir in beef, sriracha, scallion whites, half the garlic, salt (we used 3/4 tsp kosher salt; 11/2 tsp for 4), and pepper. Form into two 1-inch-tall loaves (four loaves for 4). Place on one side of a baking sheet. Toss carrots on empty side of same sheet with a drizzle of oil, salt, and pepper. (For 4, spread meatloaves out across whole sheet and add carrots to a second sheet.) Bake for 20 minutes (we'll glaze the meatloaves then).\r\n\r\n3. Meanwhile, place potatoes in a medium pot with enough salted water to cover by 2 inches. Bring to a boil and cook until very\r\ntender, 12-15 minutes. Reserve 1/2 cup potato cooking liquid, then drain. While potatoes cook, in a small bowl, combine soy sauce, garlic powder, 1/4 cup ketchup (1/2 cup for 4 servings), and 2 tsp sugar (4 tsp for 4).\r\n\r\n4. Once meatloaves and carrots have baked 20 minutes, remove from oven. Spoon half the ketchup glaze over meatloaves (save\r\nthe rest for serving); return to oven until carrots are browned and tender, meatloaves are cooked through, and glaze is tacky, 4-5 minutes more.\r\n\r\n5. Meanwhile, melt 2 TBSP butter (4 TBSP for 4 servings) in pot used for potatoes over medium heat. Add remaining garlic and cook\r\nuntil fragrant, 30 seconds. Add potatoes and 1/4 tsp wasabi. Mash, adding splashes of reserved potato cooking liquid as necessary until smooth. Season with salt and pepper. (If you like things spicy, stir in more wasabi!)\r\n\r\n6. Divide meatloaves, mashed potatoes, and roasted carrots between plates. Sprinkle with scallion greens and serve with remaining ketchup glaze on the side for dipping.",
    ingredients: [
      { name: "Potatoes", measure: "5" },
      { name: "Carrots", measure: "12 ounces" },
      { name: "Scallions", measure: "1" },
      { name: "Garlic", measure: "2 cloves" },
      { name: "Bread", measure: "1 Slice" },
      { name: "Garlic Powder", measure: "1" },
      { name: "Soy Sauce", measure: "2" },
      { name: "Ground Beef", measure: "1" },
      { name: "Vegetable Oil", measure: "1 tsp " },
      { name: "Sugar", measure: "2 tsp" },
      { name: "Butter", measure: "2 tbsp" },
      { name: "", measure: " " },
      { name: "", measure: " " },
      { name: "", measure: " " },
      { name: "", measure: " " },
      { name: "", measure: " " },
      { name: "", measure: " " },
      { name: "", measure: " " },
      { name: "", measure: " " },
      { name: "", measure: " " },
      {},
    ],
  },
];
